include build/make/target/board/generic_arm64_ab/BoardConfig.mk
include device/phh/treble/board-base.mk

ifeq ($(BOARD_SYSTEMIMAGE_PARTITION_RESERVED_SIZE),)
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2147483648
else
BOARD_SYSTEMIMAGE_PARTITION_RESERVED_SIZE := 33554432
endif

BUILD_BROKEN_PHONY_TARGETS := true

TARGET_SCREEN_WIDTH := 1080
TARGET_SCREEN_HEIGHT := 1920

WITH_SU := true
WITHOUT_CHECK_API := true
